language: ruby
rvm:
- 2.2.2

node_js:
- 0.12

cache:
  bundler: true
  directories:
  - node_modules

before_install:
- npm install --dev

script:
- npm run test-travis

env:
  global:
  - secure: kKGFgIOoYIhGy44qRWnxwYNBj+n7lGd79tn6eo9NfD3fNYFRCqZgWLJ8SGui9OW+ySA2UXdKfB2gDYJB1CaXQVRSrVrVJzj62mqE4TxDOmEbhSwCMzOkX1fLkCsZZP8KmWNTHm996XsoXD6zGkN/04KOIIu6V0Va5j/fD2zDi7/SNetggReiCkfYsDqL5JUnWWTlRWiT6XGAyrruKgz2Ds6kI4rd2ci3YtiFlbJx/ShRVBwpH4+LSQD3jLb84Ge4BfA1+ZVjg2eHBeir7CvAIJdCQ1gk9dqVk+m6+exB1Kddiy5H/y6TpntEpYybA8/1Ki1BSgnvBlIroHCUPp/27UCWXaIg9zdITeoQ+x0aEOGgtCNHWVVqSH3nuKlBviRlpiM5B4Dt1pJ2vXWnxbQQhdFiv9duNe1bfP15AHCuXNtgOXYxRAakH3DyZX5EfGGwwHP/DNRjmXCW7/n+/kY8tkI4PgOeK7Dl5Fie9L3iZ5MYYfxp0A76RF+Vi54ABh1W7V2HZFiTRmJSNnrI7WE3ydRrc+I1uKVN6opkutwwxEANAxfHxywyOdFd8HYfoEqeH62RKJuf/nUFcw3oIzt2Cvzg4u0+z2gjTmXC4CBS48Z8y7Nqt5mJl/CyJrwMU1FybEhU/vKDmD+s+gs1UTR2PrbjihcBghN8s7T/CT7s/OE=
  - secure: kl/vtsIDiLSikbhlOQsjXpEYZ9+n/PY1sBshRwrhfLlVhE5WJwngsa1hFpMCOCI7DKzUADDs57hKSVDYmv6BJFC/oX5L3dZqSxW1J5TY3L0Yhxk1Byjiv5P31hbES1P24QAouxa0oOvQf7mqLEigqO6lv2zmllDwJ665ETjzrs14wxwKEEjr51R6Hl8pb61RdClYibFtbSzEaryZowAlgfp9ogn4c1MesVmpSbdX4khqKJCrcBczP7OJHCTmzbIUj7p+rNpfPm7OM9uUHC+6O80IPyV5141XioKVF8cm+4LaPWNRJrC1PSmPcTL6D614yvNQt8OcCUAhi3WUiPb+HnlnVZWWfhq6QfoTwXn1EZSe61W7KKKRFmiiVzBfoQ5KiTVzw8jXKIDFEvkKu1TSlv2XFl7QBDxjtknZphxM8/c/0OvopgTrP18c3huqrfsUhxxkdS/BNcbgrHVtv1qFzAbimYQkAeEzFVTdHFiycXwx0UoQsrQ1RJF7MY8CxiOyNIag4oOKaUQdaB9vo0cKFuRBQRUbKiZvGqpdSAv4/F/NYSy/iuo/Hw/4TACcJ07SQku4pIwO3dsAIgGg6KwJQ7kanJgdIwvHrFqBfC5Z20ckHDWKtgIPxwkT1bG2m2DPPd1JL1dkFtClYTWVm4h+j4qO7yOjEgBXwb6JS04FPQ8=
