# Site settings
title: College Choice

description:
  Write an awesome description for your new site here.

baseurl: "/college-choice" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

sass:
  style: nested

# common site scripts, relative to `{{ site.baseurl }}/js/`
scripts:
  - vendor/aight.min.js
  - vendor/d3.min.js
  - vendor/querystring.min.js
  - vendor/document-register-element.min.js
  - components/picc-accordion.js
  - components/picc-meter.js
  - components/picc-range.js
  - picc.js

stylesheets:
  - styles.css

# API configuration
api:
  baseurl: https://api.data.gov/TEST/ed/

# specify paths to exclude from copying to _site
# Note: files and directories with the '_' prefix are excluded
# automatically
exclude:
  - package.json
  - node_modules
  - '**/Makefile'
  - 'Gemfile*'
  - config.ru
