# Site settings
title: College Scorecard

description: |
    Find the college that’s the best fit for you! The U.S. Department of
    Education’s College Scorecard has the most reliable data on college costs,
    graduation, and post-college earnings.

# the subpath of your site, e.g. /blog
baseurl:

# permanent url, for use in meta references
url: https://collegescorecard.ed.gov

# app version number
version: v2.1.2

# Build settings
markdown: kramdown

sass:
  style: compressed

# common site scripts, relative to `{{ site.baseurl }}/js/`
scripts:
  # - picc.js

stylesheets:
  - styles.css

vue:
  scripts:
    - app.js
  stylesheets:
    - app.css

# whether to include the Google Analytics & DAP snippets
analytics: true

# API configuration
API:
  baseurl: https://api.data.gov/ed/collegescorecard/v1/
  key: ''
  # API key used for API Key Signup form.
  signup_key: ''

# Captcha key used to protect from submissions
recaptcha-site-key: ''

# Google Maps API key
api-key-google-maps: ''

downloads:
  data-dictionary: CollegeScorecardDataDictionary.xlsx
  data-base_url: https://ed-public-download.app.cloud.gov/downloads

# specify paths to exclude from copying to _site
# Note: files and directories with the '_' prefix are excluded
# automatically
exclude:
  # Node and JS asset build files
  - package.json
  - node_modules
  - js/**/*.md
  - '**/Makefile'
  - '*.sh'
  # Ruby stuff
  - 'Gemfile*'
  - config.ru
  # functional testing files
  - test/**
  # see test/circle.yml for why this is necessary
  - tmp
  - vendor
  - '*.vue' 
  - js/src/*
  - __tests
  - output
