# Site settings
title: College Scorecard

description:
  Helping prospective college students find the right school.

# the subpath of your site, e.g. /blog
baseurl: /college-choice

# app version number
version: v1.2.3

# Build settings
markdown: kramdown

sass:
  style: compressed

# common site scripts, relative to `{{ site.baseurl }}/js/`
scripts:
  - picc.js

stylesheets:
  - styles.css

# whether to include the Google Analytics & DAP snippets
analytics: true

# API configuration
API:
  baseurl: https://api.data.gov/TEST/ed/production/v1/
  key: ''

# specify paths to exclude from copying to _site
# Note: files and directories with the '_' prefix are excluded
# automatically
exclude:
  # Node and JS asset build files
  - package.json
  - node_modules
  - js/**/*.md
  - '**/Makefile'
  - '*.sh'
  # Ruby stuff
  - 'Gemfile*'
  - config.ru
  # functional testing files
  - test/**
