version: '3'
services:
  web:
    build: .
    command: jekyll serve --host 0.0.0.0 --baseurl '' -w -i --force_polling --trace
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    env_file: .env
  node:
    image: node:12.20.0-alpine3.12
    working_dir: /myapp
    volumes:
      - .:/myapp
    env_file: .env
    # Keep container running for building
    command: tail -f /dev/null
